### ISSUE TITLE
ефективність запиту

### ISSUE THREAD

**Issue by pecourses** [Illiakalinin/sequelize-phones-hw#1]
https://github.com/Illiakalinin/sequelize-phones-hw/blob/4c897122cb98b4a5a80bc9534d76aad98569cea6/index.js#L34
- оскільки тут умова не на групу, то її ефективніше буде записати в where:
```
  const foundPhones = await Phone.findAll({
    raw: true,
    where: sequelize.where(
      sequelize.literal('EXTRACT (YEAR FROM manufactured_year)'),
      2011
    ),
  });
```
Тут трохи складніший синтаксис: https://sequelize.org/docs/v6/core-concepts/model-querying-basics/#advanced-queries-with-functions-not-just-columns, але суть та сама.

**Comment by pecourses** [comment]
- або як в наступному реалізованому запиті

**Comment by Illiakalinin** [comment]
> - або як в наступному реалізованому запиті

Я спочатку, чомусь, про having згадав, а потім, у наступному завданні, про where, і тому вирішив лишити в такому вигляді, щоб було використано обидва варіанти

**Comment by pecourses** [comment]
- закріпити різні підходи теж корисно)
- головне в комерційному коді в подальшому пам'ятати про ефективність)
